server:
    port: 8080

spring:
    datasource:
        url: jdbc:h2:.
        username: sa
        password:
        driver-class-name: org.h2.Driver

    jpa:
        hibernate:
            ddl-auto: create-drop